site_name: Trilha de Aprendizado para Business Intelligence - Vitru Educação
theme:
  name: material
  docs_dir: docs
  language: pt-BR
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - typeset
    - search
  palette:
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Modo noturno
nav:
  - Início: index.md
  - Comece aqui:
    - Profissional de BI: 01-comece-aqui/profissional_de_bi.md
    - Como se organizar para os estudos: 01-comece-aqui/como_organizar_estudos.md
    - Definição, história e fundamentos: 01-comece-aqui/definicao_historia_fundamentos.md
  - Aprendendo SQL:
    - Introdução ao SQL: 02-aprendendo-sql/introducao_sql.md
    - Sintaxe básica: 02-aprendendo-sql/sintaxe_basica.md
    - Filtros e seleção de intervalos: 02-aprendendo-sql/filtros_selecao_intervalos.md
    - Group by e funções de agregação: 02-aprendendo-sql/group_by.md
    - Junções (JOINS): 02-aprendendo-sql/joins.md
    - UNION e EXCEPT: 02-aprendendo-sql/union_except.md
    - Funções de data e conversões de tipos: 02-aprendendo-sql/funcoes_data.md
    - Funções de texto: 02-aprendendo-sql/funcoes_texto.md
    - Funções condicionais: 02-aprendendo-sql/funcoes_condicionais.md
  - Visualizações de dados com Power BI:
    - Jornada I:
      - Segmentações: 03-powerbi-dataviz/jornada-I/segmentacao.md
      - Gráfico de Área: 03-powerbi-dataviz/jornada-I/grafico_area.md
      - Gráfico de Barras e Colunas: 03-powerbi-dataviz/jornada-I/grafico_coluna_e_barra.md
      - Gráfico de Linhas: 03-powerbi-dataviz/jornada-I/grafico_linha.md
      - Gráfico Combinado: 03-powerbi-dataviz/jornada-I/grafico_combinado.md
      - Gráfico de Pizza e Rosca: 03-powerbi-dataviz/jornada-I/grafico_pizza.md
      - Gráfico de Medidor: 03-powerbi-dataviz/jornada-I/grafico_medidor.md
      - Cartões e KPI: 03-powerbi-dataviz/jornada-I/cartao_e_kpi.md
      - Tabela e Matriz: 03-powerbi-dataviz/jornada-I/tabela_e_matriz.md
    - Jornada II:
      - Gráfico de Dispersão: 03-powerbi-dataviz/jornada-II/grafico_dispersao.md
      - Gráfico de Funil: 03-powerbi-dataviz/jornada-II/grafico_funil.md
      - Gráfico de Cascata: 03-powerbi-dataviz/jornada-II/grafico_cascata.md
      - Gráfico de Faixa de Opções: 03-powerbi-dataviz/jornada-II/grafico_faixa_de_opcoes.md
      - Gráfico de Influenciadores Principais: 03-powerbi-dataviz/jornada-II/grafico_influenciadores_principais.md
      - Árvore de Decomposição: 03-powerbi-dataviz/jornada-II/arvore_de_decomposicao.md
      - Treemaps: 03-powerbi-dataviz/jornada-II/grafico_treemap.md
  - Trabalhando com a linguagem DAX:
    - Jornada I:
      - Entendendo o contexto de linha e de filtro: 04-powerbi-dax/jornada-I/entendendo_contexto_ linha_filtro.md
      - Medidas Implícitas x Explícitas: 04-powerbi-dax/jornada-I/medidas_implicitas_x_explicitas.md
      - Relacionamentos entre tabelas: 04-powerbi-dax/jornada-I/relacionamentos_entre_tabelas.md
      - Funções de agregação: 04-powerbi-dax/jornada-I/funcoes_agregacao.md
      - Funções de contexto: 04-powerbi-dax/jornada-I/funcoes_contexto.md
      - Funções lógicas: 04-powerbi-dax/jornada-I/funcoes_logicas.md
      - Funções iterativas: 04-powerbi-dax/jornada-I/funcoes_iterativas.md
      - Funções de texto: 04-powerbi-dax/jornada-I/funcoes_texto.md
      - Funções de data e hora: 04-powerbi-dax/jornada-I/funcoes_data.md
    - Jornada II:
      - Funções de Filtro: 04-powerbi-dax/jornada-II/funcoes_filtro.md
      - Funções de Inteligencia de Tempo: 04-powerbi-dax/jornada-II/funcoes_inteligencia.md
      - Funções de Relação: 04-powerbi-dax/jornada-II/funcoes_relacao.md
      - Funções Informativas: 04-powerbi-dax/jornada-II/funcoes_informativas.md
      - Funções de Tabela : 04-powerbi-dax/jornada-II/funcoes_tabela.md
    - Jornada III:
      - Rankings: 04-powerbi-dax/jornada-III/rankings.md
      - Funções Estatísticas: 04-powerbi-dax/jornada-III/funcoes_estatisticas.md
      - Analisando e Comparando Cenários: 04-powerbi-dax/jornada-III/analisando_cenarios.md
      - Simuladores e Projeções: 04-powerbi-dax/jornada-III/simuladores_projecoes.md
      - Analisando Segmentações: 04-powerbi-dax/jornada-III/analisando_segmentacoes.md
  - Modelagem de dados com o Power Query:
    - Jornada I:
      - Conhecendo o Power Query Editor: 05-powerbi-powerquery/jornada-I/conhecendo_power_query.md
      - Tipo dos dados: 05-powerbi-powerquery/jornada-I/tipo_dos_dados.md
      - Importação de dados: 05-powerbi-powerquery/jornada-I/importacao_dados.md
      - Gerenciar linhas e colunas: 05-powerbi-powerquery/jornada-I/gerenciar_linhas_colunas.md
      - Trabalhando com textos: 05-powerbi-powerquery/jornada-I/trabalhando_textos.md
      - Trabalhando com datas: 05-powerbi-powerquery/jornada-I/trabalhando_datas.md
      - Criando funções condicionais: 05-powerbi-powerquery/jornada-I/criando_funcoes_condicionais.md
      - Gerenciar Parâmetros: 05-powerbi-powerquery/jornada-I/gerenciar_parametros.md
      - Transpor tabelas: 05-powerbi-powerquery/jornada-I/transpor_tabelas.md
      - Relacionamentos: 05-powerbi-powerquery/jornada-I/relacionamentos.md
    - Jornada II:
      - Combinando consultas: 05-powerbi-powerquery/jornada-II/combinando_consultas.md
      - Mesclando consultas: 05-powerbi-powerquery/jornada-II/mesclando_consultas.md
      - Agrupamento e sumarização: 05-powerbi-powerquery/jornada-II/agrupamento_sumarizacao.md
      - Consulta nula e o editor avançado: 05-powerbi-powerquery/jornada-II/consulta_nula_editor_avancado.md
      - Invocar função personalizada: 05-powerbi-powerquery/jornada-II/invocar_funcao_personalizada.md
      - Calendário Padrão: 05-powerbi-powerquery/jornada-II/calendario_padrao.md
  - Power BI Serviço:
    - Introdução ao Power BI Online, Navegação e Interface: 06-powerbi-servico/jornada-I/introducao_powerbi_online.md
    - Compartilhar e Colaborar: 06-powerbi-servico/jornada-I/compartilhar_colaborar.md
    - Conceitos de Workspaces, Dataflows e Datasets: 06-powerbi-servico/jornada-I/conceitos_workspaces.md
    - Conceitos Gateway e Conexões: 06-powerbi-servico/jornada-I/conceitos_gateway_conexoes.md
    - Permissões: 06-powerbi-servico/jornada-I/permissoes.md
    - Licenciamento: 06-powerbi-servico/jornada-I/licenciamento.md
    - Assinatura de Relatórios: 06-powerbi-servico/jornada-I/assinatura_relatorios.md
  - Conceitos de Dataviz:
    - Jornada I:
      - Storytelling com Dados: 07-dataviz/jornada-I/storytelling_dados.md
    - Jornada II:
      - UX/UI para Power BI Desktop: 07-dataviz/jornada-II/ux_ui_powerbi_desktop.md
  - Conclusão:
    - Conclusão: 08-conclusao/conclusao.md
